### ISSUE TITLE
Access grant

### ISSUE THREAD

**Issue by Kumopascaline** [sas-bergson/Mobile-ERP-Store#4]
Sir i have tried to push into the depository but i don't have the access rights...
My push has been denied by Github! 

*Can you Grant me access rights to the repository* ? 
_My username is *Kumopascaline*_

**Comment by sas-bergson** [comment]
Good evening @Kumopascaline 
Noted
Trying to fix your problem
I just hope you have created the appropriate branches before pushing

**Comment by sas-bergson** [comment]
@Kumopascaline 

I just sent you an invitation to collaborate to the repository.
Please check it out

**Comment by ghost** [comment]
sir i wish have the invitation to participate to this repository
